### ISSUE TITLE
SSH Timeouts on Centos 6 tests

### ISSUE THREAD

**Issue by myoung34** [puppetlabs/beaker#718] opened 2015-02-26 19:13 UTC
```
marcuss-mbp:mirthconnect $ which beaker
/Users/myoung/.rvm/gems/ruby-2.1.1/bin/beaker
marcuss-mbp:mirthconnect $ beaker --version
      wWWWw
      |o o|
      | O |  2.5.0!
      |(")|
     / \X/ \
    |   V   |
    |   |   | 
Beaker completed successfully, thanks.
marcuss-mbp:mirthconnect $ vagrant -v
Vagrant 1.7.2
marcuss-mbp:mirthconnect $ VBoxManage --version
4.3.20r96996
```

```
arcuss-mbp:mirthconnect $ bundle exec rspec spec/acceptance/yum_spec.rb 
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
/Users/myoung/.rvm/gems/ruby-2.1.1/gems/beaker-rspec-5.0.1/lib/beaker-rspec/helpers/serverspec.rb:43: warning: already initialized constant Module::VALID_OPTIONS_KEYS
/Users/myoung/.rvm/gems/ruby-2.1.1/gems/specinfra-2.15.1/lib/specinfra/configuration.rb:4: warning: previous definition of VALID_OPTIONS_KEYS was here
Beaker::Hypervisor, found some vagrant boxes to create
==> centos-65-x64: Forcing shutdown of VM...
==> centos-65-x64: Destroying VM and associated drives...
Bringing machine 'centos-65-x64' up with 'virtualbox' provider...
==> centos-65-x64: Importing base box 'centos-65-x64-vbox436-nocm'...
==> centos-65-x64: Matching MAC address for NAT networking...
==> centos-65-x64: Setting the name of the VM: defaultyml_centos-65-x64_1424977684025_39823
==> centos-65-x64: Clearing any previously set network interfaces...
==> centos-65-x64: Preparing network interfaces based on configuration...
    centos-65-x64: Adapter 1: nat
    centos-65-x64: Adapter 2: hostonly
==> centos-65-x64: Forwarding ports...
    centos-65-x64: 22 => 2222 (adapter 1)
==> centos-65-x64: Running 'pre-boot' VM customizations...
==> centos-65-x64: Booting VM...
==> centos-65-x64: Waiting for machine to boot. This may take a few minutes...
    centos-65-x64: SSH address: 127.0.0.1:2222
    centos-65-x64: SSH username: vagrant
    centos-65-x64: SSH auth method: private key
    centos-65-x64: Warning: Connection timeout. Retrying...
    centos-65-x64: Warning: Remote connection disconnect. Retrying...
    centos-65-x64: 
    centos-65-x64: Vagrant insecure key detected. Vagrant will automatically replace
    centos-65-x64: this with a newly generated keypair for better security.
    centos-65-x64: 
    centos-65-x64: Inserting generated public key within guest...
    centos-65-x64: Removing insecure key from the guest if its present...
    centos-65-x64: Key inserted! Disconnecting and reconnecting using new SSH key...
==> centos-65-x64: Machine booted and ready!
==> centos-65-x64: Checking for guest additions in VM...
==> centos-65-x64: Setting hostname...
==> centos-65-x64: Configuring and enabling network interfaces...
==> centos-65-x64: Mounting shared folders...
    centos-65-x64: /vagrant => /Users/myoung/repos/github/puppet/mirthconnect/.vagrant/beaker_vagrant_files/default.yml
Allocated a PTY on 10.255.244.198 for "sudo su -c \"cp -r .ssh /root/.\""
Allocated a PTY on 10.255.244.198 for "sudo su -c \"sed -ri 's/^#?PermitRootLogin no|^#?PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config\""
Allocated a PTY on 10.255.244.198 for "sudo -E /sbin/service sshd restart"
Warning: Try 1 -- Host 10.255.244.198 unreachable: connection closed by remote host
```

failed on centos 6.5 (the one i've always used which worked):

```
---
HOSTS:
   centos-65-x64:
     roles:
       - master
     platform: centos-65-x64-virtualbox-puppet
     box: centos-65-x64-virtualbox-puppet
     box_url: http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box
     hypervisor: vagrant
     distmoduledir: /etc/puppet/modules
```

updated my nodeset to the alternate 6.5 (nocm which puppetlabs-mysql uses)

```
---
HOSTS:
  centos-65-x64:
    roles:
      - master
    platform: el-6-x86_64
    box : centos-65-x64-vbox436-nocm
    box_url : http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box
    hypervisor : vagrant
```

Happened on beaker 2.0.0 as well, bundle update got beaker to 2.5.0 and it continued.

**Comment by anodelman** [comment] 2015-02-26 19:14
Will be fixed with https://github.com/puppetlabs/beaker/pull/712

**Comment by myoung34** [comment] 2015-02-26 19:15
If that's the issue you can close this as a dupe and i'll have no hurt feelings. The only ones I found that were relevant were docker provisioners.

**Comment by anodelman** [comment] 2015-02-26 19:19
Yeah, dupe of https://github.com/puppetlabs/beaker/issues/702.

**Closed by anodelman** 2015-02-26 19:19 UTC
