### ISSUE TITLE
Beaker 2.1.0 fails on creation of Docker containers with RHEL6 image

### ISSUE THREAD

**Issue by lightfa** [puppetlabs/beaker#611] opened 2015-01-09 10:36 UTC
Since upgrading to Beaker 2.1.0 I have been unable to successfully provision Docker containers using a Redhat 6 docker image.

It looks like it fails when trying to restart the sshd service.

```
beaker::Hypervisor, found some docker boxes to create
Provisioning docker
provisioning beaker4
Creating image
Dockerfile is         FROM vrtstdkr001:8080/lightfa/beaker
          RUN yum clean all
          RUN yum install -y sudo openssh-server openssh-clients curl ntpdate
          RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
          RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
        RUN mkdir -p /var/run/sshd
        RUN echo root:root | chpasswd
        EXPOSE 22
        CMD /usr/sbin/sshd -D
post
/v1.12/build
{:rm=>true}
Dockerfile0000640000000000000000000000061300000000000013245 0ustar00wheelwheel00000000000000        FROM vrtstdkr001:8080/lightfa/beaker
          RUN yum clean all
          RUN yum install -y sudo openssh-server openssh-clients curl ntpdate
          RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
          RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
        RUN mkdir -p /var/run/sshd
        RUN echo root:root | chpasswd
        EXPOSE 22
        CMD /usr/sbin/sshd -D

Creating container from image 137049ceb16c
post
/v1.12/containers/create
{}
{"Image":"137049ceb16c","Hostname":"beaker4"}
Starting container cc75e9c3e4a56ae509f15144f32a075dc160634b66782fbd5fe3f3ed65380a25
post
/v1.12/containers/cc75e9c3e4a56ae509f15144f32a075dc160634b66782fbd5fe3f3ed65380a25/start
{}
{"PublishAllPorts":true,"Privileged":true}
get
/v1.12/containers/cc75e9c3e4a56ae509f15144f32a075dc160634b66782fbd5fe3f3ed65380a25/json
{}

get
/v1.12/containers/cc75e9c3e4a56ae509f15144f32a075dc160634b66782fbd5fe3f3ed65380a25/json
{}

node available as  ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@0.0.0.0 -p 49233

beaker4 10:23:57$ rpm -q curl
Created ssh connection to 0.0.0.0, user: root, opts: {:password=>"root", :port=>"49233", :forward_agent=>false, :user=>"root"}
curl-7.19.7-37.el6_5.3.x86_64

beaker4 executed in 0.20 seconds

beaker4 10:23:57$ rpm -q ntpdate
ntpdate-4.2.6p5-1.el6.x86_64

beaker4 executed in 0.02 seconds

beaker4. 10:23:57$ echo "/usr/bin"
/usr/bin

beaker4 executed in 0.01 seconds

beaker4 10:23:57$ echo "/opt/puppet-git-repos/hiera/bin"
/opt/puppet-git-repos/hiera/bin

beaker4  executed in 0.01 seconds

beaker4 10:23:57$ echo "/opt/puppet-git-repos/hiera/lib"
/opt/puppet-git-repos/hiera/lib

beaker4 executed in 0.01 seconds

beaker4 10:23:57$ echo "/opt/puppet-git-repos/hiera-puppet/lib"
/opt/puppet-git-repos/hiera-puppet/lib

beaker4 executed in 0.01 seconds
setting local environment on beaker4

beaker4 10:23:57$ echo '
PermitUserEnvironment yes' >> /etc/ssh/sshd_config

beaker4 executed in 0.01 seconds

beaker4  10:23:57$ /sbin/service sshd restart
Stopping sshd: /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `select': closed stream (IOError)
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `io_select'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:73:in `available_for_read?'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:85:in `next_packet'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:178:in `block in poll_message'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `loop'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `poll_message'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:460:in `dispatch_incoming_packets'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/ssh_connection.rb:96:in `try_to_execute'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/ssh_connection.rb:107:in `execute'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/host.rb:271:in `block in exec'
        from /usr/local/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/host.rb:270:in `exec'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/host_prebuilt_steps.rb:489:in `block in set_env'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/shared/host_manager.rb:74:in `run_block_on'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/shared/host_manager.rb:71:in `block in run_block_on'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/shared/host_manager.rb:70:in `map'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/shared/host_manager.rb:70:in `run_block_on'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/dsl/patterns.rb:32:in `block_on'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/host_prebuilt_steps.rb:471:in `set_env'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/hypervisor.rb:111:in `configure'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:71:in `block in configure'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:70:in `each_key'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:70:in `configure'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/beaker_shim.rb:43:in `configure'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/spec_helper.rb:42:in `block in <top (required)>'
        from /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core.rb:120:in `configure'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/spec_helper.rb:5:in `<top (required)>'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec.rb:5:in `<module:BeakerRSpec>'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `rescue in require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'
        from /etc/puppet/environments/dev/modules/varnish/spec/spec_helper_acceptance.rb:2:in `<top (required)>'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/cli.rb:44:in `block in initialize'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/cli.rb:43:in `each'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/cli.rb:43:in `initialize'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/bin/beaker:6:in `new'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/bin/beaker:6:in `<top (required)>'
        from /usr/local/bin/beaker:23:in `load'
        from /usr/local/bin/beaker:23:in `<main>'
``

If I comment out line 132 of beaker/hypervisor.rb 
i.e. # set_env(@hosts, @options)

Then it will successfully provision the Docker container, but it doesn't find any tests to run.

The command I am using to run the tests is
beaker --log-level trace  --hosts spec/acceptance/nodesets/default.yml --helper /etc/puppet/environments/dev/modules/varnish/spec/spec_helper_acceptance.rb --tests /etc/puppet/environments/dev/modules/varnish/spec/acceptance/standard_spec.rb

The host yaml file is as follows

```yaml
HOSTS:
  beaker4:
    roles:
      - master
      - agent
    platform: el-6-x86_64
    image:  vrtstdkr001:8080/lightfa/beaker
    hypervisor: docker
    docker_preserve_image: false
CONFIG:
  type: foss
  log_level: verbose
```

It looks like restarting the ssh service closes the connection to the image and this causes the process to fail? I am missing something?

Thanks
Andy

**Comment by petems** [comment] 2015-01-09 21:26
@lightfa Here's a Centos Docker image that works for me:

```yaml
HOSTS:
  centos-6-x64:
    roles:
      - master
      - database
      - dashboard
    platform: el-6-x86_64
    image: electrical/centos:6.4
    hypervisor: docker
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'yum install -y wget ntpdate rubygems ruby-augeas ruby-devel augeas-devel'
      - 'touch /etc/sysconfig/network'
    docker_preserve_image: true
CONFIG:
  type: foss
```

Does that work for you if you change the image to the one you want?

**Comment by lightfa** [comment] 2015-01-12 15:18
Thanks Peter. 

Unfortunately that doesn't seem to work for me either.

It fails with the same error as before when performing the sshd restart.

Is there a dependency on a specific version of Docker? (I'm running 1.1.2)

beaker4 15:14:22$ /sbin/service sshd restart
Stopping sshd: /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `select': closed stream (IOError)
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `io_select'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:73:in `available_for_read?'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:85:in `next_packet'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:178:in `block in poll_message'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `loop'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `poll_message'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:460:in `dispatch_incoming_packets'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/ssh_connection.rb:96:in `try_to_execute'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/ssh_connection.rb:107:in `execute'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/host.rb:271:in `block in exec'
        from /usr/local/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/host.rb:270:in `exec'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/host_prebuilt_steps.rb:489:in `block in set_env'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/shared/host_manager.rb:74:in `run_block_on'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/shared/host_manager.rb:71:in `block in run_block_on'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/shared/host_manager.rb:70:in `map'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/shared/host_manager.rb:70:in `run_block_on'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/dsl/patterns.rb:32:in `block_on'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/host_prebuilt_steps.rb:471:in `set_env'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/hypervisor.rb:111:in `configure'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:71:in `block in configure'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:70:in `each_key'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:70:in `configure'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/beaker_shim.rb:43:in `configure'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/spec_helper.rb:42:in `block in <top (required)>'
        from /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.0/lib/rspec/core.rb:120:in `configure'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/spec_helper.rb:5:in `<top (required)>'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec.rb:5:in `<module:BeakerRSpec>'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `rescue in require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'
        from /etc/puppet/environments/dev/modules/varnish/spec/spec_helper_acceptance.rb:2:in `<top (required)>'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/cli.rb:44:in `block in initialize'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/cli.rb:43:in `each'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/cli.rb:43:in `initialize'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/bin/beaker:6:in `new'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/bin/beaker:6:in `<top (required)>'
        from /usr/local/bin/beaker:23:in `load'
        from /usr/local/bin/beaker:23:in `<main>'

**Comment by petems** [comment] 2015-01-12 17:03
I'm on 1.4.1, and from looking at the docker API docs it looks like they expect 1.3

Can you try upgrading and seeing if that helps?

**Comment by lightfa** [comment] 2015-01-12 17:06
Yes that sound like a good idea I'll try a later version of docker. Will update with results.

Thanks again

**Comment by carlossg** [comment] 2015-01-14 18:47
dupe of #567 ?

**Comment by carlossg** [comment] 2015-01-14 19:43
Maybe it's different.

What is happening is that docker container is running sshd as the main process, and when beaker executes the ssh restart the container is stopped/killed with the main process

**Comment by carlossg** [comment] 2015-01-15 13:04
A workaround, add to the hosts config:

``` yaml
    docker_image_commands:
      - "sed -ri 's/^#?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config"
      - "sed -ri 's/^#?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config"
    docker_cmd:
      - 'sh'
      - '-c'
      - 'service ssh start; tail -f /dev/null'
```

**Comment by lightfa** [comment] 2015-01-16 11:33
The workaround is working (with a slight amendment to use service sshd instead of service ssh) and the docker container can be provisioned by beaker.


Thanks for your help with this.

**Comment by anodelman** [comment] 2015-01-26 19:08
We're tracking docker ssh restart issues in PRs so I'm going to close this out.

**Closed by anodelman** 2015-01-26 19:08 UTC
