### ISSUE TITLE
Beaker/vagrant ssh issues on centos6

### ISSUE THREAD

**Issue by lavaman** [puppetlabs/beaker#702] opened 2015-02-18 21:29 UTC
I'm having a problem getting beaker tests to run on centos boxes. I did a clean clone of puppetlabs-apache on a new osx yosemite and after sshd_config gets the sed and restarts, ssh fails. A vagrant reload makes it work again, but I can't get single-run tests working. I've tried on centos-64 and centos-65 with the same results. I've verified this works fine on ubuntu-server-1404. Using included nodesets and puppetlabs vagrant boxes. Debug output in gist:
https://gist.github.com/lavaman/9ee69ee1075f6629a938

**Comment by lavaman** [comment] 2015-02-18 23:47
Tried putting in delay and doing a second restart here:
https://github.com/puppetlabs/beaker/blob/master/lib/beaker/host_prebuilt_steps.rb#L347
Still no luck.

**Comment by anodelman** [comment] 2015-02-19 00:06
What vagrant version are you using?

**Comment by lavaman** [comment] 2015-02-19 00:07
latest. (1.7.2)

**Comment by anodelman** [comment] 2015-02-19 00:07
Attempting to reproduce now.

**Comment by lavaman** [comment] 2015-02-19 00:13
You may have to manually install nokogiri to point it at the right libxml2 dir:
http://stackoverflow.com/questions/19643153/error-to-install-nokogiri-on-osx-10-9-maverick
The first answer has the command for Yosemite.

**Comment by anodelman** [comment] 2015-02-19 00:14
My nokogiri installed no problem, beaker worked fine on vagrant centos5 box - testing centos6 now.

**Comment by lavaman** [comment] 2015-02-19 00:18
Here is my bundle list as well, just in case:
Using rake 10.4.2
Using CFPropertyList 2.3.0
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0
Using addressable 2.3.7
Using archive-tar-minitar 0.5.2
Using extlib 0.9.16
Using multi_json 1.10.1
Using autoparse 0.3.3
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using aws-sdk-v1 1.62.0
Using aws-sdk 1.62.0
Using excon 0.44.2
Using docker-api 1.19.0
Using fission 0.5.0
Using builder 3.2.2
Using formatador 0.2.5
Using mime-types 2.4.3
Using net-ssh 2.9.2
Using net-scp 1.2.1
Using fog-core 1.28.0
Using fog-xml 0.1.1
Using fog-atmos 0.1.0
Using fog-json 1.0.0
Using ipaddress 0.8.0
Using fog-aws 0.1.0
Using inflecto 0.0.2
Using fog-brightbox 0.7.1
Using fog-ecloud 0.0.2
Using fog-profitbricks 0.0.1
Using fog-radosgw 0.0.3
Using fog-sakuracloud 1.0.0
Using fog-serverlove 0.1.1
Using fog-softlayer 0.4.1
Using fog-storm_on_demand 0.1.0
Using fog-terremark 0.0.4
Using fog-vmfusion 0.0.1
Using fog-voxel 0.0.2
Using fog 1.27.0
Using multipart-post 2.0.0
Using faraday 0.9.1
Using launchy 2.4.3
Using retriable 1.4.1
Using jwt 1.2.1
Using signet 0.6.0
Using google-api-client 0.8.2
Using hocon 0.0.7
Using inifile 2.0.2
Using trollop 2.1.1
Using rbvmomi 1.8.2
Using unf_ext 0.0.6
Using unf 0.1.4
Using beaker 2.4.1
Using rspec-support 3.1.2
Using rspec-core 3.1.7
Using diff-lcs 1.2.5
Using rspec-expectations 3.1.2
Using rspec-mocks 3.1.3
Using rspec 3.1.0
Using rspec-its 1.1.0
Using specinfra 2.14.1
Using serverspec 2.8.2
Using beaker-rspec 5.0.1
Using docile 1.1.5
Using facter 1.7.6
Using json_pure 1.8.2
Using hiera 1.3.4
Using metaclass 0.0.4
Using mocha 1.1.0
Using puppet 3.7.4
Using puppet-lint 1.1.0
Using puppet-syntax 1.4.1
Using puppet_facts 0.2.1
Using rspec-puppet 1.0.1
Using puppetlabs_spec_helper 0.8.2
Using simplecov-html 0.9.0
Using simplecov 0.9.2
Using bundler 1.8.0

**Comment by anodelman** [comment] 2015-02-19 00:20
Recreated with centos6 - so, it's either a very platform specific bug or there's a misconfiguration in our provided vagrant boxes.  I'll investigate further tomorrow.  For now, try to use something other than centos6.  :)

**Comment by lavaman** [comment] 2015-02-19 00:20
Good to know it's not just me :)
Thanks

**Comment by hohum** [comment] 2015-02-23 03:45
I know what this is because I still have to use el6 for a bit.  It was fixed in https://github.com/puppetlabs/beaker/pull/545 but then rebroken in https://github.com/puppetlabs/beaker/issues/656

**Comment by bknowles** [comment] 2015-02-23 18:02
So, this is the change you want to undo, right?

<code>
git diff 61cb832 10ac746
diff --git a/61cb832 b/10ac746
index 61cb832..10ac746 100644
--- a/61cb832
+++ b/10ac746
@@ -344,7 +344,7 @@ module Beaker
         if host['platform'] =~ /debian|ubuntu|cumulus/
           host.exec(Command.new("sudo su -c \"service ssh restart\""), {:pty => true})
         elsif host['platform'] =~ /centos|el-|redhat|fedora|eos/
-          host.exec(Command.new("sudo -E /sbin/service sshd restart"))
+          host.exec(Command.new("sudo -E /sbin/service sshd restart"), {:pty => true})
         else
           @logger.warn("Attempting to update ssh on non-supported platform: #{host.name}: #{host['platform']}")
         end
</code>

**Comment by lavaman** [comment] 2015-02-23 18:12
I don't think reverting will fix this. I have verified that a service reload works per:
https://github.com/hohum/beaker/commit/82b1cb09dc965d3b1ea592b6adbd6396ffd9ac67

**Comment by bknowles** [comment] 2015-02-23 23:15
I have also confirmed that the service reload from https://github.com/hohum/beaker/commit/82b1cb09dc965d3b1ea592b6adbd6396ffd9ac67 does work.

I built my own version of the gem versions 2.4.1.1 and installed that, and it works whereas the current 2.4.1 gem does not.

Thanks!

**Comment by anodelman** [comment] 2015-03-02 18:39
In PR, merge blocking on review comments.  https://github.com/puppetlabs/beaker/pull/712

**Comment by anodelman** [comment] 2015-03-09 23:10
In new PR  https://github.com/puppetlabs/beaker/pull/740

**Comment by anodelman** [comment] 2015-03-10 18:33
merged.

**Closed by anodelman** 2015-03-10 18:33 UTC
