### ISSUE TITLE
Beaker fails with docker hypervisior after beaker 2.0.0 release

### ISSUE THREAD

**Issue by cardil** [puppetlabs/beaker#567] opened 2014-12-09 12:39 UTC
Hi,

I been testing my modules with docker/beaker. It has been working before 2.0.0 release. Now it throws exception on `net-ssh`:

```
$ rvm --version
rvm 1.26.0 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ bundle --version
Bundler version 1.7.4
gem --version
2.4.2
ruby --version
ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-linux]
$ bundle exec rake acceptance RS_SET=centos-65-x64-docker
/home/ksuszynski/.rvm/rubies/ruby-2.1.4/bin/ruby -S rspec spec/acceptance
Beaker::Hypervisor, found some docker boxes to create
Provisioning docker
provisioning centos-65-x64-docker
Warning: Try 1 -- Host 0.0.0.0 unreachable: connection closed by remote host
Warning: Trying again in 1 seconds
/home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `select': closed stream (IOError)
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `io_select'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:73:in `available_for_read?'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:85:in `next_packet'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:178:in `block in poll_message'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `loop'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `poll_message'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:460:in `dispatch_incoming_packets'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/ssh_connection.rb:96:in `try_to_execute'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/ssh_connection.rb:107:in `execute'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/host.rb:270:in `block in exec'
	from /home/ksuszynski/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/host.rb:269:in `exec'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/host_prebuilt_steps.rb:495:in `block in set_env'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/shared/host_manager.rb:74:in `run_block_on'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/shared/host_manager.rb:71:in `block in run_block_on'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/shared/host_manager.rb:70:in `map'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/shared/host_manager.rb:70:in `run_block_on'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/dsl/patterns.rb:32:in `block_on'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/host_prebuilt_steps.rb:477:in `set_env'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/hypervisor.rb:110:in `configure'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/network_manager.rb:71:in `block in configure'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/network_manager.rb:70:in `each_key'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/network_manager.rb:70:in `configure'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/beaker_shim.rb:43:in `configure'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/spec_helper.rb:42:in `block in <top (required)>'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core.rb:154:in `configure'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/spec_helper.rb:5:in `<top (required)>'
	from /home/ksuszynski/git/xtreemfs/spec/spec_helper_acceptance.rb:1:in `require'
	from /home/ksuszynski/git/xtreemfs/spec/spec_helper_acceptance.rb:1:in `<top (required)>'
	from /home/ksuszynski/git/xtreemfs/spec/acceptance/001_role/001_directory_spec.rb:1:in `require'
	from /home/ksuszynski/git/xtreemfs/spec/acceptance/001_role/001_directory_spec.rb:1:in `<top (required)>'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `block in load_spec_files'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `each'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load_spec_files'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:18:in `run'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:103:in `run'
	from /home/ksuszynski/git/xtreemfs/.vendor/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:17:in `block in autorun'
/home/ksuszynski/.rvm/rubies/ruby-2.1.4/bin/ruby -S rspec spec/acceptance failed
```

to replicate issue just:
```
git clone https://github.com/wavesoftware/puppet-xtreemfs.git
cd puppet-xtreemfs
rvm use 2.1
bundle install --without development --path .vendor
bundle exec rake acceptance RS_SET=centos-65-x64-docker
```

**Comment by electrical** [comment] 2015-01-05 17:52
@cardil @tfhartmann @Yuav can you guys try the master branch of beaker and beaker-rspec?
It should all be fixed now.
If not please let us know.

**Comment by tfhartmann** [comment] 2015-01-05 21:26
Sure! Here's what I get with a hosts.yaml file that looks like this (just centos)  Maybe it's just that SSH isn't running on the centos image?

```Yaml
HOSTS:
  centos6:
    platform: centos-6-x64
    image: centos:centos6
    hypervisor: docker
    docker_preserve_image: true
CONFIG:
  type: foss

```

```Shell
Beaker::Hypervisor, found some docker boxes to create
Provisioning docker
provisioning centos6
Warning: Try 1 -- Host 0.0.0.0 unreachable: connection closed by remote host
Warning: Trying again in 1 seconds
Failed: errored in CLI.provision
#<IOError: closed stream>
/usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/bundler/gems/beaker-b78580a7ccc0/bin/beaker:6
Cleanup: cleaning up after failed run
/usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:122:in `close': closed stream (IOError)
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:122:in `shutdown!'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:127:in `shutdown!'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/bundler/gems/beaker-b78580a7ccc0/lib/beaker/ssh_connection.rb:66:in `rescue in close'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/bundler/gems/beaker-b78580a7ccc0/lib/beaker/ssh_connection.rb:63:in `close'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/bundler/gems/beaker-b78580a7ccc0/lib/beaker/host.rb:249:in `close'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/bundler/gems/beaker-b78580a7ccc0/lib/beaker/network_manager.rb:89:in `block in cleanup'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/bundler/gems/beaker-b78580a7ccc0/lib/beaker/network_manager.rb:89:in `each'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/bundler/gems/beaker-b78580a7ccc0/lib/beaker/network_manager.rb:89:in `cleanup'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/bundler/gems/beaker-b78580a7ccc0/lib/beaker/cli.rb:114:in `rescue in execute!'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/bundler/gems/beaker-b78580a7ccc0/lib/beaker/cli.rb:77:in `execute!'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/bundler/gems/beaker-b78580a7ccc0/bin/beaker:6:in `<top (required)>'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/bin/beaker:23:in `load'
	from /usr/local/rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/bin/beaker:23:in `<main>'
```

**Comment by electrical** [comment] 2015-01-05 21:31
@tfhartmann feels like its a SSH issue indeed in the image.
I use different images that launch /sbin/init so i can manage ( and test ) the actual services parts as well
You can take a look at my node set files https://github.com/elasticsearch/puppet-elasticsearch/tree/master/spec/acceptance/nodesets how i've done it.

Cheers.

**Comment by cassianoleal** [comment] 2015-01-08 12:40
I can confirm that adding `docker_cmd: '["/sbin/init"]'` to the host configuration works around this issue on CentOS 6 images. Here's my full nodeset if someone is interested:

```
---
HOSTS:
  centos6:
    roles:
      - master
    platform: el-6-x86_64
    image: chef/centos-6
    hypervisor: docker
    docker_cmd: '["/sbin/init"]'
    docker_preserve_image: false
CONFIG:
  type: foss
```

**Comment by anodelman** [comment] 2015-01-12 18:35
This looks docker image dependent?  Any beaker changes required?  Better documentation?

**Comment by cassianoleal** [comment] 2015-01-13 10:32
I'm not sure, but I can say that the same docker image works fine with Beaker < 2.0.0

**Comment by anodelman** [comment] 2015-01-26 19:10
The issue here is the ssh restart required by beaker to add options to the ssh environment.  We are currently tracking in PRs.

**Comment by tfhartmann** [comment] 2015-02-23 14:54
Any chance we might see PuppetLabs images on the docker hub, something similar to the puppetlabs vagrant boxes?

**Comment by anodelman** [comment] 2015-02-23 16:49
Unlikely, for now.  Our internal testing is done on ec2, vsphere and openstack - so we don't have docker in the mix.

**Comment by tfhartmann** [comment] 2015-02-23 16:50
:sob:

**Comment by anodelman** [comment] 2015-03-10 18:35
We've switched to an ssh service reload.  This should be resolved.

**Closed by anodelman** 2015-03-10 18:35 UTC

**Comment by tfhartmann** [comment] 2015-03-10 19:01
Thanks! @anodelman
